name: Build APK

# Ejecutar el flujo en cada push o pull request a la rama main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout
        uses: actions/checkout@v4

      # Instalar dependencias de Buildozer
      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev automake
          pip install --user --upgrade Cython==0.29.33 virtualenv
          pip install --user --upgrade buildozer
          echo 'export PATH=$PATH:~/.local/bin/' >> ~/.bashrc

      # Configurar Java (necesario para Android SDK)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Compilar el APK con Buildozer
      - name: Build APK
        run: |
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          sudo update-java-alternatives --set ${JAVA_HOME}
          export PATH=$JAVA_HOME/bin:$PATH
          buildozer -v android debug

      # Subir el APK como artefacto
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
